### ISSUE TITLE
SwtBot launch is broken?

### ISSUE THREAD

**Issue by frankbenoit** [ssi-schaefer/lcdsl#83]
The launch config worked before.
Now with target platform 2024-06 for the application and in the host IDE com.wamas.ide.launching.feature.feature.group 0.6.0.202405271742
````
!SESSION 2024-07-31 07:49:38.526 -----------------------------------------------
eclipse.buildId=unknown
java.version=21.0.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -version 3 -port 59342 -testLoaderClass org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader -loaderpluginname org.eclipse.jdt.junit5.runtime -classNames .... -application org.eclipse.swtbot.eclipse.core.swtbottestapplication -product com.....product -testpluginname com....
Command-line arguments:  -console -consoleLog -version 3 -port 59342 -testLoaderClass org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader -loaderpluginname org.eclipse.jdt.junit5.runtime -classNames com.....Test -application org.eclipse.swtbot.eclipse.core.swtbottestapplication -product com.....product -data C:\..\ws/../runtime-test -dev file:C:/Work/.../ws/.metadata/.plugins/org.eclipse.pde.core/com....Test/dev.properties -console -consoleLog -os win32 -ws win32 -arch x86_64 -testpluginname com.....

!ENTRY org.eclipse.osgi 4 0 2024-07-31 07:49:44.527
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.eclipse.swtbot.eclipse.core.swtbottestapplication" could not be found in the registry. The applications available are: org.eclipse.ant.core.antRunner, org.eclipse.cdt.core.GeneratePDOM, org.eclipse.cdt.core.CodeFormatter, org.eclipse.e4.ui.workbench.swt.E4Application, org.eclipse.e4.ui.workbench.swt.GenTopic, org.eclipse.equinox.app.error, org.eclipse.equinox.p2.garbagecollector.application, org.eclipse.equinox.p2.publisher.InstallPublisher, org.eclipse.equinox.p2.publisher.EclipseGenerator, org.eclipse.equinox.p2.publisher.ProductPublisher, org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher, org.eclipse.equinox.p2.touchpoint.natives.nativePackageExtractor, org.eclipse.help.base.infocenterApplication, org.eclipse.help.base.helpApplication, org.eclipse.help.base.indexTool, org.eclipse.jdt.core.JavaIndexer, org.eclipse.pde.junit.runtime.uitestapplication, org.eclipse.pde.junit.runtime.coretestapplication, org.eclipse.pde.junit.runtime.coretestapplicationnonmain, org.eclipse.pde.junit.runtime.nonuithreadtestapplication, org.eclipse.ui.ide.workbench.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:264)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:34)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
````

To fix this, I needed to add `plugin org.eclipse.swtbot.eclipse.core;`
This was not needed before.
Is this expected or a bug?

**Comment by haubi** [comment]
Regarding the "worked before":
Was it before you upgraded to target platform 2024-06, or before you upgraded to lcdsl 0.6.0.202405271742?

**Comment by frankbenoit** [comment]
I did try an install in my current IDE, here the versions of other plugins like extend were downgraded as well.
With 0.5.0 it does not resolve the needed plugins for the test, hence the "Validations" dialog pops up.
